# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluate.score_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from finalscore import Ui_Dialog as Score  #Score window
import sqlite3
match= sqlite3.connect("fantasy_cricket.db")
matchcur=match.cursor()



class Ui_evaluate_team(object):
    def __init__(self):  #initialising score window
        self.scoreDialog = QtWidgets.QMainWindow()
        self.score_screen = Score()
        self.score_screen.setupUi(self.scoreDialog)
    
    def setupUi(self, evaluate_team):
        evaluate_team.setObjectName("evaluate_team")
        evaluate_team.resize(571, 561)
        evaluate_team.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(evaluate_team)
        self.label.setGeometry(QtCore.QRect(40, 30, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.select_team_cb = QtWidgets.QComboBox(evaluate_team)
        self.select_team_cb.setGeometry(QtCore.QRect(100, 80, 151, 31))
        font = QtGui.QFont()
        # font.setFamily("Comic Sans MS")
        font.setFamily("Arial")
        font.setPointSize(10)
        self.select_team_cb.setFont(font)
        self.select_team_cb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.select_team_cb.setObjectName("select_team_cb")
        self.select_team_cb.addItem("")
        self.select_match_cb = QtWidgets.QComboBox(evaluate_team)
        self.select_match_cb.setEnabled(True)
        self.select_match_cb.setGeometry(QtCore.QRect(330, 80, 151, 31))
        font = QtGui.QFont()
        # font.setFamily("Comic Sans MS")
        font.setFamily("Arial")
        font.setPointSize(10)
        self.select_match_cb.setFont(font)
        self.select_match_cb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.select_match_cb.setObjectName("select_match_cb")
        self.select_match_cb.addItem("")
        self.frame = QtWidgets.QFrame(evaluate_team)
        self.frame.setGeometry(QtCore.QRect(50, 170, 469, 289))
        self.frame.setStyleSheet("background-color: rgb(221, 221, 221);")
        # self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        # self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.players_lw = QtWidgets.QListWidget(self.frame)
        self.players_lw.setGeometry(QtCore.QRect(40, 40, 181, 231))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.players_lw.setFont(font)
        self.players_lw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.players_lw.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.players_lw.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.players_lw.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.players_lw.setObjectName("players_lw")
        self.scores_lw = QtWidgets.QListWidget(self.frame)
        self.scores_lw.setGeometry(QtCore.QRect(250, 40, 181, 231))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scores_lw.setFont(font)
        self.scores_lw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scores_lw.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scores_lw.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.scores_lw.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.scores_lw.setObjectName("scores_lw")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(0)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(330, 10, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(3, 106, 117);")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(evaluate_team)
        self.line.setGeometry(QtCore.QRect(30, 120, 511, 20))
        self.line.setStyleSheet("color: rgb(170, 255, 255);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.score_btn = QtWidgets.QPushButton(evaluate_team)
        self.score_btn.setEnabled(True)
        self.score_btn.setGeometry(QtCore.QRect(230, 490, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.score_btn.setFont(font)
        self.score_btn.setStyleSheet("background-color: rgb(5, 162, 165);\n"
"color: rgb(255, 255, 255);")
        self.score_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.score_btn.setAutoDefault(False)
        self.score_btn.setObjectName("score_btn")

        self.retranslateUi(evaluate_team)
        self.select_team_cb.setCurrentIndex(0)
        self.select_match_cb.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(evaluate_team)

        self.score_btn.clicked.connect(self.final_score)
        selected_team = self.select_team_cb.currentText()

        self.changedname(selected_team)
        self.select_team_cb.currentTextChanged.connect(self.changedname)

    def retranslateUi(self, evaluate_team):
        _translate = QtCore.QCoreApplication.translate
        evaluate_team.setWindowTitle(_translate("evaluate_team", "Calculate Score"))
        self.label.setText(_translate("evaluate_team", "Evaluate the performance of your Fancy Team!"))
        self.select_team_cb.setCurrentText(_translate("evaluate_team", "Select team"))
        self.select_team_cb.setItemText(0, _translate("evaluate_team", "select team"))
        self.select_match_cb.setItemText(1, _translate("evaluate_team", "Match1"))
        self.select_match_cb.setItemText(0, _translate("evaluate_team", "select match"))
        self.label_2.setText(_translate("evaluate_team", "Players"))
        self.label_3.setText(_translate("evaluate_team", "Points"))
        self.label_4.setText(_translate("evaluate_team", "0"))
        self.score_btn.setStatusTip(_translate("evaluate_team", "calculating score"))
        self.score_btn.setText(_translate("evaluate_team", "Calculate Score"))
        x = matchcur.execute("SELECT  DISTINCT name from teams;")
        team = x.fetchall()
        for i in team:
            self.select_team_cb.addItem(i[0])
    def changedname(self, t):
        self.players_lw.clear()
        self.scores_lw.clear()
        y = matchcur.execute("SELECT players from teams WHERE name='" + t + "';")
        player = y.fetchall()
        
        # print('player',player)
        for j in player:
            self.players_lw.addItem(j[0])
        z = matchcur.execute("SELECT value from teams WHERE name='" + t + "';")
        value = z.fetchall()
        for k in value:
            self.scores_lw.addItem(str(k[0]))


    def final_score(self):
        total_score=0
        t=self.select_team_cb.currentText()   # current teamname
        # print(t)
        z = matchcur.execute("SELECT value from teams WHERE name='" + t + "';")
        value = z.fetchall()
       
        # print('value', value)
        for k in value:
            total_score+=k[0]
        self.score_screen.final_score.setText(str(total_score))  # opening score dialog box and setting final score
        self.scoreDialog.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    evaluate_team = QtWidgets.QDialog()
    ui = Ui_evaluate_team()
    ui.setupUi(evaluate_team)
    evaluate_team.show()
    sys.exit(app.exec_())
