# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_team_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_team(object):
    def setupUi(self, new_team):
        new_team.setObjectName("new_team")
        new_team.resize(420, 184)
        new_team.setStyleSheet("background-color: rgb(237, 255, 255);")
        self.label = QtWidgets.QLabel(new_team)
        self.label.setGeometry(QtCore.QRect(20, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.team_name = QtWidgets.QLineEdit(new_team)
        self.team_name.setGeometry(QtCore.QRect(140, 50, 251, 31))
        self.team_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.team_name.setObjectName("team_name")
        self.savename = QtWidgets.QPushButton(new_team)
        self.savename.setGeometry(QtCore.QRect(180, 120, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.savename.setFont(font)
        self.savename.setStyleSheet("background-color: rgb(5, 162, 165);\n"
"color: rgb(255, 255, 255);")
        self.savename.setObjectName("savename")

        self.retranslateUi(new_team)
        QtCore.QMetaObject.connectSlotsByName(new_team)

    def retranslateUi(self, new_team):
        _translate = QtCore.QCoreApplication.translate
        new_team.setWindowTitle(_translate("new_team", "New Team"))
        self.label.setText(_translate("new_team", "Team Name"))
        self.team_name.setPlaceholderText(_translate("new_team", "enter new team name"))
        self.savename.setText(_translate("new_team", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_team = QtWidgets.QDialog()
    ui = Ui_new_team()
    ui.setupUi(new_team)
    new_team.show()
    sys.exit(app.exec_())
