# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_team_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
match=sqlite3.connect('fantasy_cricket.db')
matchcur=match.cursor()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 184)
        Dialog.setStyleSheet("background-color: rgb(237, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.open_team = QtWidgets.QComboBox(Dialog)
        self.open_team.setGeometry(QtCore.QRect(140, 50, 251, 31))
        self.open_team.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.open_team.setObjectName("open_team")
        self.openname = QtWidgets.QPushButton(Dialog)
        self.openname.setGeometry(QtCore.QRect(180, 120, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.openname.setFont(font)
        self.openname.setStyleSheet("background-color: rgb(5, 162, 165);\n"
"color: rgb(255, 255, 255);")
        self.openname.setObjectName("openname")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        teams= matchcur.execute("SELECT DISTINCT name FROM teams;")  # fetching team names
        y= teams.fetchall()
        for i in y:
            self.open_team.addItem(i[0])


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Open Team"))
        self.label.setText(_translate("Dialog", "Team Name"))
        self.openname.setText(_translate("Dialog", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
